# Generated by Django 5.2.7 on 2025-10-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="comment",
            new_name="ratings_com_user_id_ce05d1_idx",
            old_name="rating_comm_user_id_c9bf5d_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="ratings_com_movie_i_5adcaa_idx",
            old_name="rating_comm_movie_i_88c1f6_idx",
        ),
        migrations.RenameIndex(
            model_name="rating",
            new_name="ratings_rat_user_id_eac68b_idx",
            old_name="rating_rati_user_id_70d8d1_idx",
        ),
        migrations.RenameIndex(
            model_name="rating",
            new_name="ratings_rat_movie_i_2277eb_idx",
            old_name="rating_rati_movie_i_f7080e_idx",
        ),
        migrations.RenameIndex(
            model_name="rating",
            new_name="ratings_rat_score_5b2efc_idx",
            old_name="rating_rati_score_2870dc_idx",
        ),
    ]
