# Generated by Django 5.2.7 on 2025-11-01 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        help_text="Stripe event identifier",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe event ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type of webhook event",
                        max_length=100,
                        verbose_name="event type",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Full webhook payload", verbose_name="payload"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the event was processed",
                        verbose_name="processed",
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        verbose_name="processing error",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook event",
                "verbose_name_plural": "webhook events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_event_id"],
                        name="payment_web_stripe__35d41a_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="payment_web_event_t_4c8ed7_idx"
                    ),
                    models.Index(
                        fields=["processed"], name="payment_web_process_b8a5f3_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="payment_web_created_f0fadf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        help_text="Stripe PaymentIntent identifier",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe payment intent ID",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Checkout Session identifier",
                        max_length=255,
                        verbose_name="Stripe checkout session ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in USD",
                        max_digits=10,
                        verbose_name="amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Payment currency code",
                        max_length=3,
                        verbose_name="currency",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        help_text="Payment status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "subscription_months",
                    models.IntegerField(
                        default=1,
                        help_text="Number of subscription months",
                        verbose_name="subscription months",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Payment description",
                        verbose_name="description",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the payment was completed",
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="payment_pay_user_id_2df5ec_idx",
                    ),
                    models.Index(
                        fields=["stripe_payment_intent_id"],
                        name="payment_pay_stripe__46a826_idx",
                    ),
                    models.Index(
                        fields=["stripe_checkout_session_id"],
                        name="payment_pay_stripe__fb7465_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payment_pay_status_124d3d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        help_text="Stripe customer identifier",
                        max_length=255,
                        unique=True,
                        verbose_name="Stripe customer ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe customer",
                "verbose_name_plural": "Stripe customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="payment_str_user_id_583472_idx"
                    ),
                    models.Index(
                        fields=["stripe_customer_id"],
                        name="payment_str_stripe__9443c0_idx",
                    ),
                ],
            },
        ),
    ]
